project_id = "hlqhwgmkutmjsiuegmei"

[functions.generate-blog-image]
verify_jwt = false

[functions.generate-blog-content]
verify_jwt = false

[functions.generate-web-results]
verify_jwt = false

[functions.generate-prelander]
verify_jwt = false
